# Generated by Django 4.2.30 on 2026-06-30 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_customrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_number', models.CharField(max_length=50)),
                ('letter_date', models.CharField(max_length=30)),
                ('period_range', models.CharField(blank=True, default='', max_length=100)),
                ('item_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('reserved_numbers', models.JSONField(default=list)),
                ('final_letter_number', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_approvals', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_number', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('period_range', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('approved', 'approved'), ('rejected', 'rejected')], default='draft', max_length=20)),
                ('amount', models.BigIntegerField(default=0)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='invoices/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='accounts.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='invoices.itemtype')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('customer_type', models.CharField(choices=[('legal', 'legal'), ('natural', 'natural')], default='legal', max_length=10)),
                ('national_id', models.CharField(blank=True, default='', max_length=20)),
                ('economic_code', models.CharField(blank=True, default='', max_length=20)),
                ('registration_number', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payers', to='accounts.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='invoices.payer')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('tracking_number', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.company')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoices.payer')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ManualDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_debts', to='accounts.company')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_debts', to='invoices.payer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, default='', max_length=100)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.CharField(blank=True, default='', max_length=30)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('debt', models.BigIntegerField(default=0)),
                ('credit', models.BigIntegerField(default=0)),
                ('balance', models.BigIntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.itemtype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ItemTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date'), ('select', 'select')], default='text', max_length=10)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='invoices.itemtype')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('item_type', 'key')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.itemtype'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.payer'),
        ),
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_number', models.CharField(max_length=50)),
                ('file_type', models.CharField(choices=[('invoice', 'invoice'), ('notice', 'notice'), ('creditor', 'creditor')], max_length=20)),
                ('file', models.FileField(upload_to='finance/generated/')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('is_deleted_from_disk', models.BooleanField(default=False)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='invoices.approvalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('credit_date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='accounts.company')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='invoices.payer')),
            ],
            options={
                'ordering': ['-credit_date'],
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='invoices.payer'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LetterSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_2digit', models.CharField(max_length=2)),
                ('last_number', models.IntegerField(default=0)),
                ('prefix', models.CharField(default='', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_sequences', to='accounts.company')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_sequences', to='invoices.payer')),
            ],
            options={
                'unique_together': {('company', 'payer', 'year_2digit')},
            },
        ),
        migrations.CreateModel(
            name='ItemFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_number', models.BigIntegerField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.itemtypefield')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='invoices.lineitem')),
            ],
            options={
                'unique_together': {('line_item', 'field')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('company', 'letter_number')},
        ),
    ]
