# Generated by Django 4.2.30 on 2026-07-08 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_user_can_approve_user_can_delete_history_and_more'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedfile',
            name='file_format',
            field=models.CharField(choices=[('excel', 'Excel'), ('word', 'Word'), ('pdf', 'PDF'), ('html', 'HTML')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='generatedfile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedfile',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedfile',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_files', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='generatedfile',
            name='approval_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='invoices.approvalrequest'),
        ),
        migrations.CreateModel(
            name='FileTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc_kind', models.CharField(choices=[('invoice', 'صورتحساب'), ('notice', 'اطلاعیه واریز'), ('creditor', 'بستانکاری'), ('letter', 'نامه رسمی')], max_length=20)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='finance/templates/docx/')),
                ('html_content', models.TextField(blank=True, default='', help_text='HTML template with Jinja2 placeholders')),
                ('css_content', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('placeholders', models.JSONField(blank=True, default=list, help_text='List of available {{placeholder}} names')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_templates', to='accounts.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doc_kind', 'name'],
            },
        ),
    ]
