# Generated by Django 4.2.30 on 2026-07-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_generatedfile_file_format_generatedfile_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdebt',
            name='service_type',
            field=models.CharField(blank=True, choices=[('ویزا', 'ویزا'), ('اتوبوس', 'اتوبوس'), ('قطار', 'قطار'), ('گشت', 'گشت'), ('تور', 'تور'), ('CIP', 'CIP'), ('سایر', 'سایر')], default='', max_length=50),
        ),
    ]
